var index = [
{'name': 'io.github.weakish.zeronet.zerome.crawler', 'type': 'package', 'url': 'index.html#section-package', 'doc': '<p>Given a hub, produce a category of hubs\nwith Link(A, B) as the morphism.</p>', 'tags': [],'icons': ['icon-package']},
{'name': 'UsageError.exit_code', 'type': 'value', 'url': 'UsageError.type.html#exit_code', 'doc': '<p><code>ex_usage</code> i.e. command line usage error (sysexits.h)</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'UsageError', 'type': 'class', 'url': 'UsageError.type.html', 'doc': '<p>Command line usage error, e.g. missing argument for option.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'read_file', 'type': 'function', 'url': 'index.html#read_file', 'doc': '<p>Read the file whole.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'load_json_object', 'type': 'function', 'url': 'index.html#load_json_object', 'doc': '<p>Returns null if parsed result of file is not JsonObject.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'LoadJsonFail.exit_code', 'type': 'value', 'url': 'LoadJsonFail.type.html#exit_code', 'doc': '<p><code>ex_dataerr</code> i.e. data format error (sysexits.h)</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'LoadJsonFail', 'type': 'class', 'url': 'LoadJsonFail.type.html', 'doc': '<p>When failed to parse a string as json object.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'get_json_string', 'type': 'function', 'url': 'index.html#get_json_string', 'doc': '<p>Given a json object and a key, returns object[key] iff object[key] is a string.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'meta', 'type': 'function', 'url': 'index.html#meta', 'doc': '<p>Parse content.json of a hub for meta data.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'HubLinks', 'type': 'alias', 'url': 'index.html#HubLinks', 'doc': '<p>A set of hub IDs.</p>', 'tags': [],'icons': ['icon-type-alias']},
{'name': 'HubMeta', 'type': 'alias', 'url': 'index.html#HubMeta', 'doc': '<p>title, description, zeronet_version</p>', 'tags': [],'icons': ['icon-type-alias']},
{'name': 'Hub', 'type': 'alias', 'url': 'index.html#Hub', 'doc': '<p>hub_id -> [HubMeta, HubLinks]</p>', 'tags': [],'icons': ['icon-type-alias']},
{'name': 'Hubs', 'type': 'alias', 'url': 'index.html#Hubs', 'doc': '<p>A set of <code><a class=\'link\' href=\'index.html#Hub\' title=\'Go to io.github.weakish.zeronet.zerome.crawler::Hub\'>Hub</a></code>s.</p>', 'tags': [],'icons': ['icon-type-alias']},
{'name': 'resolve_directory', 'type': 'function', 'url': 'index.html#resolve_directory', 'doc': '<p>Resolve a link to direcotry.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'resolve_file', 'type': 'function', 'url': 'index.html#resolve_file', 'doc': '<p>Resolve a link to direcotry.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'resolve_path_to_file', 'type': 'function', 'url': 'index.html#resolve_path_to_file', 'doc': '<p>Resolve a path to a flie.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'resolve_path_to_directory', 'type': 'function', 'url': 'index.html#resolve_path_to_directory', 'doc': '<p>Resolve a path to a direcotry.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'get_follow', 'type': 'function', 'url': 'index.html#get_follow', 'doc': '<p>Returns non empty follow array.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'crawl_links', 'type': 'function', 'url': 'index.html#crawl_links', 'doc': '<p>Given a <strong>hub</strong> site path, returns all hub IDs whose users are followed by the given <strong>hub</strong>.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'crawl', 'type': 'function', 'url': 'index.html#crawl', 'doc': '<p>Gluing code or the real entry point.\nR</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'jsonify', 'type': 'function', 'url': 'index.html#jsonify', 'doc': '<p>Returns JsonObject for <code><a class=\'link\' href=\'index.html#Hub\' title=\'Go to io.github.weakish.zeronet.zerome.crawler::Hub\'>Hub</a></code> and JsonArray of JsonObject for <code><a class=\'link\' href=\'index.html#Hubs\' title=\'Go to io.github.weakish.zeronet.zerome.crawler::Hubs\'>Hubs</a></code>.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'get_userdb_dir', 'type': 'function', 'url': 'index.html#get_userdb_dir', 'doc': '<p>Returns <code>data/REGISTRY_ID/data/userdb/</code>.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'crawl_all', 'type': 'function', 'url': 'index.html#crawl_all', 'doc': '<p>Returns</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'crawl_all_hubs', 'type': 'function', 'url': 'index.html#crawl_all_hubs', 'doc': '<p>Crawl zerome user register for hubs.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'run', 'type': 'function', 'url': 'index.html#run', 'doc': '<p>The ultimate exception handler.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'io.github.weakish.zeronet.zerome.crawler', 'type': 'module', 'url': 'index.html', 'doc': '<p>A module to crawl zerome hubs.</p>', 'tags': [],'icons': ['icon-module']}];
var tagIndex = [
];
